### ISSUE TITLE
Feedback on bb experience

### ISSUE THREAD

**Issue by borkdude** [lambdaisland/gaiwan_co#12]
Hi @oxalorg! I noticed you moved to standard clojure for the gaiwan site.

I noticed this because I was referring someone to this project on how to build a small site with bb, lol :)

I don't see this as something bad: many small projects start as a small bb script and then outgrow it and move to the JVM. Makes total sense. However, to improve babashka I would like to learn from this.

I see you are making a script here to install bootleg:
https://github.com/lambdaisland/gaiwan_co/commit/cca390520c115d2d9eac71ae1cd54afb2b32d1c3

This isn't necessary anymore since bb 0.2.6 (release a few weeks ago) can now install pods on its own from the pod registry.
See this example: https://github.com/babashka/pod-registry/blob/master/examples/bootleg.clj#L5

I am planning to add a hiccup namespace to babashka in the future.
Bb also has a small web server which allows you to preview it

If you have feedback on why you moved to "standard" clojure, let me know and maybe there's something that can be improved for the next person trying bb for this purpose.

EDIT:

Forgot to mention, you can now load deps.edn with babashka as well:

https://book.babashka.org/#babashkadeps

So for both pods and classpath deps, you can now do this using a bb script, without reverting to bash.

Thanks!

**Comment by oxalorg** [comment]
Hey @borkdude thank you for all the awesome work you've been doing with Babashka! I really love using babaska for small stuff here and there.

Firstly, I've created a branch pointing to the last commit where we're still using `bb` so that it's easier to share & show someone the power of bb: https://github.com/lambdaisland/gaiwan_co/tree/babashka-bootleg

My reason for moving away from Babashka / Bootleg are actually quite silly, and not really a limitation of `bb`.
* I could not get the bb repl working on calva on my windows machine, though it worked perfectly well on linux/emacs setup
* The bb wrapper / bootleg installation seemed a bit hacky, I only wanted to rely on clj deps as I was trying to use Github Actions for deployment and I couldn't figure out how (I think pod registry would solve this)
* Wasn't sure how I would integrate clojure libraries which may not support sci or play well with babashka's pod API. I'm still a bit confused as I haven't tried, but I felt a bit uneasy as I was diverging from the standard conventions. This might also make it difficult for some other devs on our team to contribute to the project if they are not familiar with how `bb` works
* I wanted to use ring, our css libs like ornament and garden, and some other stuff in the future and I wasn't sure if everything would work well with bb and bootleg combo
* Script build time was not an issue. If the site generates 1-2s slower it is not a deal breaker for us 

I think it would be fair to say that this decision was mostly out of my own lack of clear understanding of the tradeoffs I would be making if I stuck to babashka + bootleg. And also my lack of understanding of what benefit babashka was offering / would offer in the future.

Also some more examples of real world babashka scripts being used would definitely have given me a more clear understanding of where babashka shines.

**Comment by borkdude** [comment]
Thanks for writing this! I'll close the issue now.
